// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessaPedido.Infrastructure.Persistence;

#nullable disable

namespace ProcessaPedido.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250604011310_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("ProcessaPedido.Domain.Entities.Entrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("PedidoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("ProcessaPedido.Domain.Entities.ItemEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntregaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntregaId");

                    b.ToTable("ItemEntrega");
                });

            modelBuilder.Entity("ProcessaPedido.Domain.Entities.Entrega", b =>
                {
                    b.OwnsOne("ProcessaPedido.Domain.Entities.Destinatario", "Destinatario", b1 =>
                        {
                            b1.Property<Guid>("EntregaId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("EntregaId");

                            b1.ToTable("Entregas");

                            b1.WithOwner()
                                .HasForeignKey("EntregaId");
                        });

                    b.Navigation("Destinatario")
                        .IsRequired();
                });

            modelBuilder.Entity("ProcessaPedido.Domain.Entities.ItemEntrega", b =>
                {
                    b.HasOne("ProcessaPedido.Domain.Entities.Entrega", null)
                        .WithMany("Itens")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProcessaPedido.Domain.Entities.Entrega", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
