version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fila-rabbitmq
    ports:
      - "5672:5672"       # Porta usada pela aplicacao para enviar/receber mensagens
      - "15672:15672"     # Painel web de administracao
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
